### ISSUE TITLE
Incorrect units for charge density

### ISSUE THREAD

**Issue by millerk123** [UCLA-Plasma-Simulation-Group/pyVisOS#20]
Han,

It looks like your OSUnits function isn't able to handle the charge density units correctly.  The raw string specifying the charge density units in 2D is
`'e \\omega_p^2/ c^2'`,
but when I use OSUnits on that string I get
`osh5def.OSUnits at 0x2aaadbbdc1d0: ('m_e', 'c', '\\omega', 'e', 'n_0')=(0, 2, 2, 1, 0)`
instead of
`osh5def.OSUnits at 0x2aaadbbdc1d0: ('m_e', 'c', '\\omega', 'e', 'n_0')=(0, -2, 2, 1, 0)`.

Could you look into this?

Thanks,
Kyle

**Comment by Wen-Han** [comment]
Thank you for pointing this out. It is a known bug which I forgot to patch. The cause is that I didn't write a general parser for the units string. So everything is very specific to the Osiris output. It requires whitespaces around the operator '/'. Anyway I had a quick workaround. Please update to the latest dev or master.

**Comment by millerk123** [comment]
Okay, thanks so much Han!
